name=V2MIDI
version=1
author=Versio Duo
maintainer=Kay Sievers <kay@vrfy.org>
sentence=USB MIDI Packet Interface
paragraph=USB MIDI Packet Interface
category=Device Control
url=https://github.com/versioduo/V2MIDI
architectures=samd
depends=Adafruit_TinyUSB
